
name: Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/  # Adjust the path if your tests are in a different directory

      - name: Deploy to Render
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
               -d "serviceId=${{ secrets.RENDER_SERVICE_ID }}" \
               "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
